[package]
name = "ferris-is-you"
version = "0.1.0"
authors = ["mfred <6153204+mfred488@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "ferris-base",
    "ferris-terminal",
    "ferris-wasm",
]

[[bin]]
name = "ferris-is-you"
path = "ferris-terminal/src/main.rs"
